# This is a basic workflow to help you get started with Actions

name: CI

on: [push]
    
jobs:
  container:
    runs-on: ubuntu-latest
    container: shadowsocks/android-ndk-go
    steps:
      - run: |
          ./gradlew assembleDebug
        name: Run in container

